---
- hosts: localhost
  vars:
    proxy: proxy
    s390x: false
  tasks:
    - name: Build image for x86
      docker_image:
        name: dataport.de/dupover
        tag: latest
        build:
          path: .
          args:
            http_proxy: "{{ proxy }}"
            https_proxy: "{{ proxy }}"
          pull: yes
          nocache: yes
        source: build
        force_source: yes
      when: not s390x|bool
    - name: Build image for s390x
      docker_image:
        name: dataport.de/dupover
        tag: latest
        build:
          path: .
          args:
            http_proxy: "{{ proxy }}"
            https_proxy: "{{ proxy }}"
            arch: s390x
          pull: yes
          nocache: yes
        source: build
        force_source: yes
      when: s390x|bool
    - name: Create container
      docker_container:
          name: dupover
          image: dataport.de/dupover
          recreate: yes
          state: present
    - name: Create package directory
      file:
        path: dupover-0.0.1
        state: directory
        mode: 0750
    - name: Copy config file
      copy:
        src: config.yml
        dest: dupover-0.0.1/config.yml
        mode: 0660
        remote_src: yes
    - name: Copy binary from container
      shell: docker cp dupover:/go/src/app/dupover dupover-0.0.1
    - name: Create package
      archive:
        path: dupover-0.0.1
        dest: dupover-0.0.1.zip
        format: zip
    - name: Remove container
      docker_container:
        name: dupover
        state: absent
    - name: Remove image
      docker_image:
        name: dataport.de/dupover
        tag: latest
        state: absent
